### ISSUE TITLE
Upgrade grafana image to the last stable version of 8.5.x

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/grafana-k8s-operator#101]
### Enhancement Proposal

Upgrade to 8.5 so we can add Prometheus Alertmanager datasource

**Comment by simskij** [comment]
We could either do this by upgrading the datasource plugin or by upgrading the entire Grafana image to 8.5.x. I would suggest we do the latter as that would bring us to the "latest and greatest" of the 8.x.x major.
