### ISSUE TITLE
Dashboards do not survive node restart.

### ISSUE THREAD

**Issue by dstathis** [canonical/grafana-k8s-operator#104]
### Bug Description

If you restart the k8s node, all the  dasboards will be gone until you add any "grafana-dashboard" relation, at which point they are all restored.

### To Reproduce

1. `juju deploy grafana-k8s`
2. `juju deploy <anything>`
3. `juju relate grafana-k8s <anything>`
4. `sudo reboot`
5. check for dashboards

### Environment

```
dylan@protostar:~/loki$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
dylan@protostar:~/loki$ snap list
Name        Version        Rev    Tracking       Publisher   Notes
charmcraft  1.7.1          978    latest/stable  canonical✓  classic
core18      20220428       2409   latest/stable  canonical✓  base
core20      20220527       1518   latest/stable  canonical✓  base
docker      20.10.14       1779   latest/stable  canonical✓  -
juju        2.9.32         19681  latest/stable  canonical✓  classic
juju-wait   2.8.4~2.8.4    96     latest/stable  stub        classic
lxd         4.0.9-8e2046b  22753  4.0/stable/…   canonical✓  -
microk8s    v1.24.0        3272   1.24/stable    canonical✓  classic
snapd       2.56           16010  latest/stable  canonical✓  snapd
```

### Relevant log output

```shell
-
```

**Comment by simskij** [comment]
This also includes the actual endpoints.

**Comment by dstathis** [comment]
> This also includes the actual data sources.

The data sources seem to be there in my reproduction.

**Comment by rbarry82** [comment]
I looked over the rest of our libraries, and absolutely zero of them account for this case, at least in any kind of intentional fashion.

Grafana keeps all of this in peer relation data, and does try to refresh things during `on.upgrade`, but there's not even an appropriate event for "the node has been restarted". We can try to blindly hook into `pebble_ready` and check for relation data and refresh, but that pattern is... not great. Still the best that can be done
