### ISSUE TITLE
Log a warning if ingested more than one dashboard with the same id

### ISSUE THREAD

**Issue by sed-i** [canonical/grafana-k8s-operator#161]
### Enhancement Proposal

Currently, dashboards are silently omitted if the uid is not unique.

We could encounter dashboards with the same id in the following scenarios:

1. An existing dashboard is modified and exported several times (exported uid and version remain the same).
2. A dashboard is manually duplicated and modified, forgetting to change the id.
3. A dashboard is manually duplicated and modified, and id is manually changed to something else, which then in turn collides with another random dashboard.

**Comment by rbarry82** [comment]
This will not be fixed. A. baseline assumption of "the generated (U)UID from Grafana exports should actually be unique" is something we'll take for granted.

**Comment by sed-i** [comment]
> A. baseline assumption of "the generated (U)UID from Grafana exports should actually be unique" is something we'll take for granted.

Not sure what you mean:
- Currently, when you re-export the same dashboard you will get the same id.
- This issue is about logging a warning, not deduplicating the id ourselves.

**Comment by rbarry82** [comment]
I mean, very literally, that re-exporting the same dashboard and saving it as a different filename is a case we won't cover. Upstream doesn't cover it either. 

The scenario of a dashboard being manually duplicated or edited without clearing the ID (and letting Grafana generate one) or modifying it is a "don't do that" scenario for upstream Grafana also.
