### ISSUE TITLE
Grafana stuck on waiting - installing agent

### ISSUE THREAD

**Issue by Basdbruijne** [canonical/grafana-k8s-operator#162]
### Bug Description

In test run https://solutions.qa.canonical.com/v2/testruns/d4676f04-a422-47f1-a066-40a974baeebe, the deployment blocks with:

```
Model  Controller    Cloud/Region              Version  SLA          Timestamp
cos    popocatepetl  microk8s_cloud/localhost  2.9.37   unsupported  12:08:08Z

App           Version  Status   Scale  Charm             Channel  Rev  Address         Exposed  Message
alertmanager  0.23.0   active       1  alertmanager-k8s  edge      37  10.152.183.182  no       
catalogue              active       1  catalogue-k8s     edge       4  10.152.183.190  no       
grafana       9.2.1    waiting      1  grafana-k8s       edge      54  10.152.183.180  no       installing agent
loki          2.4.1    active       1  loki-k8s          edge      47  10.152.183.27   no       
prometheus    2.33.5   active       1  prometheus-k8s    edge      86  10.152.183.243  no       
traefik                active       1  traefik-k8s       edge      94  10.244.40.91    no       

Unit             Workload     Agent  Address      Ports  Message
alertmanager/0*  active       idle   10.1.35.156         
catalogue/0*     active       idle   10.1.35.145         
grafana/0        maintenance  idle                       installing charm software
loki/0*          active       idle   10.1.35.157         
prometheus/0*    active       idle   10.1.35.158         
traefik/0*       active       idle   10.1.35.155    
```

In the [microk8s crashdump](https://oil-jenkins.canonical.com/artifacts/d4676f04-a422-47f1-a066-40a974baeebe/generated/generated/microk8s/juju-crashdump-microk8s-2022-12-02-12.09.23.tar.gz) the pod logs for grafana are missing. There are some mentions of grafana in the microk8s logs, but nothing that indicates a clear failure to me.

Other logs and configs can be found here:
https://oil-jenkins.canonical.com/artifacts/d4676f04-a422-47f1-a066-40a974baeebe/index.html

### To Reproduce

Deploy microk8s 1.26, add metallb, deploy cos

### Environment

microk8s 1.26
cos-lite latest/edge

### Relevant log output

```shell
https://oil-jenkins.canonical.com/artifacts/d4676f04-a422-47f1-a066-40a974baeebe/index.html
```

**Comment by sed-i** [comment]
I wonder if it's related to resource limits. What is the VM size this is running on?

Would be handy to have the output of
```
kubectl get pods/grafana-0 -n cos -o=jsonpath='{.status}'
```
in the generated logs.

**Comment by Basdbruijne** [comment]
We did indeed get some messages complaining about memory and disk space. A larger VM seems to have fixed the problem. I will add the suggested kubectl output to the generated crashdumps.
