### ISSUE TITLE
Grafana fails with uncaught error when importing grafana 9 dashboard

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/grafana-k8s-operator#170]
### Bug Description

When relate to the application Grafana cannot parse the dashboards file. I am not 100% sure that the JSON is correct, but I just exported it from grafana and put into the folder

### To Reproduce

relate to an app with attached dashboard
[FastAPI-Monitoring.json (copy).tmpl.txt](https://github.com/canonical/grafana-k8s-operator/files/10231032/FastAPI-Monitoring.json.copy.tmpl.txt)

### Environment

- EDIT [@sed-i]: grafana-dashboard 0.16 (charm from stable).

### Relevant log output

```shell
Traceback (most recent call last):
  File "./src/charm.py", line 1156, in <module>
    main(GrafanaCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 438, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/main.py", line 150, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 856, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-grafana-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1272, in _on_grafana_dashboard_relation_changed
    changes = self._render_dashboards_and_signal_changed(event.relation)
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1372, in _render_dashboards_and_signal_changed
    content = _inject_labels(content, topology, self._tranformer)
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 729, in _inject_labels
    panels[panel_idx] = _modify_panel(panel, topology_with_prefix, transformer)
  File "/var/lib/juju/agents/unit-grafana-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 764, in _modify_panel
    elif panel["datasource"] not in known_datasources:
TypeError: unhashable type: 'dict'
```

**Comment by sed-i** [comment]
- Could you please add to the issue the LIBPATCH of the grafana_dashboard lib?
- Looks like this is a [grafana 9 dashboard](https://github.com/canonical/grafana-k8s-operator/issues/155), but with an error I haven't seen previously. Try fetch-lib?
- The filename is named `tmpl` but there are no variables there

```json
      "datasource": {
        "type": "prometheus",
        "uid": "P46F394775F18A2CC"
      }
```
Typically we'd have `${prometheusds}` there.

**Comment by beliaev-maksim** [comment]
I use `grafana_dashboard` of `LIBPATCH = 19`

reading library docs I see:
`Where the files are Grafana dashboard JSON data either from the Grafana marketplace, or directly exported from a Grafana instance.`
That sounds like I can use them unchanged. 

or is it mandatory to modify it then?

**Comment by beliaev-maksim** [comment]
updating datasources to variables does not help. And I would expect grafana still to render the dashboard, just with empty data, since source is incorrect.

see new template attached
[FastAPI-Monitoring.json.tmpl.txt](https://github.com/canonical/grafana-k8s-operator/files/10237497/FastAPI-Monitoring.json.tmpl.txt)

**Comment by sed-i** [comment]
> That sounds like I can use them unchanged.

Yep, that's correct.

This seems like a legit error:
```
    elif panel["datasource"] not in known_datasources:
TypeError: unhashable type: 'dict'
```
A dict cannot be a key.
```python
>>> d1 = {"k1": "v1"}
>>> d2 = {d1: "v2"}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'dict'
>>> d1 in {}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'dict'
```

**Comment by beliaev-maksim** [comment]
@sed-i 
thanks

**Comment by beliaev-maksim** [comment]
@sed-i @dstathis 
It looks like it fails in grafana unit. Where stable grafana uses patchlib version 16

I just checked the code for version 19 and it looks to be fixed there.

what is the plan to update the latest stable to new lib ?

**Comment by sed-i** [comment]
Yeah I don't see `elif panel["datasource"] not in known_datasources` in 0.19.
Just to be sure, can you confirm the dashboard loads with 0.19 (edge)?

**Comment by beliaev-maksim** [comment]
confirm, SSH'ed to grafana pod, replaced lib 16 to lib 19 and it works

**Comment by sed-i** [comment]
Latest release CI [failed](https://github.com/canonical/grafana-k8s-operator/actions/runs/3658389427/jobs/6183130254) because of #137. Re-running.

**Comment by sed-i** [comment]
> what is the plan to update the latest stable to new lib ?

`stable` should be stable for < grafana 9 dashboard.

`edge` hasn't passed all [quality gates](https://github.com/canonical/cos-lite-bundle/blob/main/RELEASE.md) yet, but wdyt @simskij ?

**Comment by simskij** [comment]
Closing as it works on edge
