### ISSUE TITLE
Substitute the get-admin-password-action for an action allowing to set the password

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/grafana-k8s-operator#171]
### Enhancement Proposal

I'm proposing removing current the get-admin-password  that retrieves the password stored in the charm status for another action that receives the password as a parameter and won't store it in the charm status.
The current approach constitutes a huge security risk as it both stores the password in the charm state and also the stored password can not be hashed by definition.

**Comment by PietroPasotti** [comment]
I agree that storing the password in stored state isn't great.
However, without refactoring the whole flow, we could switch the storage backend with the juju-provided secrets API, which should be secure. See https://discourse.charmhub.io/t/how-to-add-secrets-to-charms-with-the-operator-framework/7221 (might be slightly outdated)

We'd have to wait for ops 2.0 but that's worth it IMHO

Besides, setting the admin password after the application has been started already would mean a restart, I assume? Or do you propose to delay starting the app until an admin password has been set? That'd mean deploying the charm in blocked state, which isn't great either.

**Comment by arturo-seijas** [comment]
@PietroPasotti using the secrets API would certainly be an improvement but there's still a risk of the password being exposed if Juju is compromised. Hashing passwords is the standard practice to avoid unnecessary risk under there scenarios because it's a non reversible process.
I'm not sure changing the password will need a restart, it seems unlikely, and the charm can be deployed with a randomly generated password.

**Comment by PietroPasotti** [comment]
But if juju is compromised, the action payload (your plain text password) may just as well be exposed, I'm not sure I see the benefit.

**Comment by arturo-seijas** [comment]
AFAIK, the action payload is not stored, right?

**Comment by PietroPasotti** [comment]
I don't think so, I meant more that it could be snooped off of the API calls.

**Comment by simskij** [comment]
Thank you for the suggestion, Arturo!

This password is meant to be a randomized password to allow for initial login and then to be changed by the admin.

We are not looking to grow the ability to circumvent Grafana's own password change procedures. Closing as a Won't do.
