### ISSUE TITLE
Reuse dashboards across Juju applications with the same charm and version

### ISSUE THREAD

**Issue by mmanciop** [canonical/grafana-k8s-operator#21]
Grafana dashboards in Grafana should be shared across all versions of the same charm.

Dashboards in Grafana should be identified by `<charm_name>/<charm_version>`, so that we can use the grouping inside the dashboard to handle multiple instances of the same charm and allow quick comparison of, e.g., performance of various Cassandra clusters in one go.

**Comment by rbarry82** [comment]
Done as part of "stable UIDs" in #114
