### ISSUE TITLE
Enhance the grafana datasource library so that it allows creating copies of data sources with different names

### ISSUE THREAD

**Issue by simskij** [canonical/grafana-k8s-operator#219]
### Enhancement Proposal

Enhance the grafana datasource library so that it allows creating copies of data sources with different names. This will be useful for OSM, where dashboards are not created through the grafana-dashboard library, but directly over HTTP REST API calls.

So for instance, the user instantiates the DatasourceProvider, passing the optional parameter `aliases` set to `['osm_prometheus']`, which would result in two datasources, `osm_prometheus` **and** the default one, both pointing at the same prometheus instance.

If anyone (i.e. @canonical/observability) has a better solution, please chime in before we do this. :)

**Comment by Abuelodelanada** [comment]
The OSM Team will add this datasource from Mon using the Grafana admin API
