### ISSUE TITLE
Reduce grafana packing time by dropping deps

### ISSUE THREAD

**Issue by sed-i** [canonical/grafana-k8s-operator#237]
### Enhancement Proposal

- `kubernetes` is used by the old `kubernetes_service.py` file. We can use `observability_libs/v1/kubernetes_service_patch.py` instead.
- `urllib3` is convenient but we can probably use the builtin urllib.

**Comment by Abuelodelanada** [comment]
- We should go for `open_ports` instead of `kubernetes_service_patch`

**Comment by lucabello** [comment]
Done in https://github.com/canonical/grafana-k8s-operator/pull/246
