### ISSUE TITLE
Improve documentation in charmhub 

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/grafana-k8s-operator#239]
### Enhancement Proposal

Documentation in charmhub used to be more informative.
Maybe it got lost?

**Comment by dstathis** [comment]
We should copy the info in the readme to discourse. For now we can put it in the index, but, when we do our diataxis roadmap item, we should reconsider where it belongs.

**Comment by lucabello** [comment]
I believe this can be considered done now.
