### ISSUE TITLE
Reusability of upstream dashboards without forking it

### ISSUE THREAD

**Issue by nobuto-m** [canonical/grafana-k8s-operator#274]
### Enhancement Proposal

If I'm not mistaken, any dashboard JSON has to be modified to have `${prometheusds}` as the data source and the variable is COS specific as explained in:
https://github.com/canonical/grafana-k8s-operator/blob/9b3a8e3a5374f9a558ad026be246d93fb9ae9102/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L42-L43

I see that dashboard definitions even inside the COS stack are carrying over diffs from upstream just for the variable.

e.g. [node-exporter-full dashboard in grafana-agent charm](https://github.com/canonical/grafana-agent-operator/blob/49abf15ffcde20d02961118f921c34565084a310/src/grafana_dashboards/node-exporter-full.json)

```diff
diff --git b/src/grafana_dashboards/node-exporter-full.json a/src/grafana_dashboards/node-exporter-full.json
index 8b9b501..bb136f1 100644
--- b/src/grafana_dashboards/node-exporter-full.json
+++ a/src/grafana_dashboards/node-exporter-full.json
@@ -1,7 +1,7 @@
 {
   "__inputs": [
     {
-      "name": "DS_PROMETHEUS",
+      "name": "prometheusds",
       "label": "prometheus",
       "description": "",
       "type": "datasource",
@@ -66,7 +66,7 @@
       {
         "datasource": {
           "type": "prometheus",
-          "uid": "${DS_PROMETHEUS}"
+          "uid": "${prometheusds}"
         },
         "enable": true,
         "expr": "changes(node_boot_time_seconds{instance=\"$node\"}[$__rate_interval])",
@@ -104,7 +104,7 @@
       "collapsed": false,
       "datasource": {
         "type": "prometheus",
-        "uid": "${DS_PROMETHEUS}"
+        "uid": "${prometheusds}"
       },
       "gridPos": {
         "h": 1,
@@ -118,7 +118,7 @@
         {
           "datasource": {
             "type": "prometheus",
-            "uid": "${DS_PROMETHEUS}"
+            "uid": "${prometheusds}"
           },
           "refId": "A"
         }
@@ -129,7 +129,7 @@
     {
       "datasource": {
         "type": "prometheus",
-        "uid": "${DS_PROMETHEUS}"
+        "uid": "${prometheusds}"
       },
       "description": "Busy state of all CPU cores together",
       "fieldConfig": {

...
```

Could we stop forcing carrying over diffs for COS? I mean forking upstream dashboards to have Juju specific variables like `$juju_model, $juju_model_uuid, $juju_application, $juju_unit` makes sense to give a better visibility of Juju models. However, carrying over the diff just to replace a variable (`${DS_PROMETHEUS}` -> `${prometheusds}`, `$datasource` -> `${prometheusds}`) doesn't make much sense to me.

I see some logic in the code but it's only used over a legacy relation if I understand it correctly.
https://github.com/canonical/grafana-k8s-operator/blob/9b3a8e3a5374f9a558ad026be246d93fb9ae9102/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L1803-L1814

Fwiw, I have this kind of upstream dashboard JSONs in mind not to maintain a large diff over time:
https://github.com/ceph/ceph/blob/543a62fe6437bafca81d4f507e45f541886e87e0/monitoring/ceph-mixin/dashboards_out/ceph-cluster.json#L48

**Comment by simskij** [comment]
> Could we stop forcing carrying over diffs for COS? I mean forking upstream dashboards to have Juju specific variables like $juju_model, $juju_model_uuid, $juju_application, $juju_unit makes sense to give a better visibility of Juju models. However, carrying over the diff just to replace a variable (${DS_PROMETHEUS} -> ${prometheusds}, $datasource -> ${prometheusds}) doesn't make much sense to me.

I don't think we have that option, unfortunately. If this isn't done, and there is no datasource in Grafana named whatever upstream expects it to be named, the dashboard won't work once Grafana loads it as nothing is available to load the data.

We try to identify datasources and replace them with the prometheus and loki datasources, but this isn't fool proof, which is why we ask the charm authors to name them correctly from the get-go.

**Comment by lucabello** [comment]
We could try exposing the transformation logic in a script: let's explore that in #283.
