### ISSUE TITLE
Implement integration certificate_transfer with self-signed-certificates-operator

### ISSUE THREAD

**Issue by bencekov** [canonical/grafana-k8s-operator#277]
### Enhancement Proposal

We need this enhancement for Grafana to be able to integrate with the Identity Platform.

Grafana needs to trust the tls certificate of the proxy service (traefik) we use to complete an Oauth 2.0 login flow with the Identity Platform. Our proxy gets it's certificate from the [self-signed-certificates-operator](https://github.com/canonical/self-signed-certificates-operator). For authentication to work, the grafana charm needs to implement receiving the trusted cert from the self-signed-certificates-operator charm's certificate_transfer integration.

**Comment by sed-i** [comment]
Reference impl for adding cert transfer:
- https://github.com/canonical/traefik-k8s-operator/pull/204
- https://github.com/canonical/traefik-k8s-operator/pull/224

Could be a good opportunity to introduce the "tls truststore".

**Comment by lucabello** [comment]
We're planning the work for this feature; in the meantime, one possible workaround could be relating Grafana to the same **self-signed-certificates-operator** as Traefik; this will make Grafana trust the same CA and things should work.

**Comment by sed-i** [comment]
Impl'd in #279. Closing.
