### ISSUE TITLE
Grafana not able to connect to Loki when TLS with self signed cert is enabled.

### ISSUE THREAD

**Issue by peppepetra** [canonical/grafana-k8s-operator#282]
### Bug Description

After enabling TLS using tls-overlay.yaml provided by cos-lite, Grafana fails to connect to Loki.

Workaround is to remove the grafana-source relation between Loki and Grafana and add the datasource manually with Skip TLS Verify enabled

### To Reproduce

Deploy cos-lite with tls-overlay

### Environment

grafana-k8s                   edge          93
loki-k8s                      edge         105

### Relevant log output

```shell
When testing the datasource on Grafana UI the following popup message appear:

Unable to fetch labels from Loki (Failed to call resource), please check the server logs for more details
```

**Comment by simskij** [comment]
Will be handled in https://github.com/canonical/loki-k8s-operator/issues/414
