### ISSUE TITLE
Allow integration from multiple instances of the same charm without overwriting the first dashboard created

### ISSUE THREAD

**Issue by amandahla** [canonical/grafana-k8s-operator#310]
### Enhancement Proposal

I would like to integrate multiple instances of the same charm with Grafana, creating one dashboard for each integration.

Reason: deploy and integrate different versions of the charm so will not be the same dashboard for every instance integrated.

Reference:
https://matrix.to/#/!nHXpRkcSNJHlHdUGbQ:ubuntu.com/$8c6wHO28xRmdBwrGwzndugr1SZWPupyIIk3F1ebUK_I?via=ubuntu.com&via=matrix.org

**Comment by sed-i** [comment]
Currently, dashboards are intentionally named on disk this way to avoid duplicates:

```
$ juju ssh --container grafana grafana/0 ls -1 /etc/grafana/provisioning/dashboards 
default.yaml
juju_alertmanager-k8s_e9224b0.json
juju_loki-k8s_0804127.json
juju_prometheus-k8s_35dd368.json
self_dashboard.json
```

So if you're changing the contents of the dashboard, [its sha256](https://github.com/canonical/grafana-k8s-operator/blob/8dbe5785e397c9a75a7b7aafa6c84ba393b5f812/src/charm.py#L631) would change and the dashboards won't overwrite each other.

One way of forcing it is modifying the [dashboard's uid](https://github.com/canonical/alertmanager-k8s-operator/blob/af82fec475aa143799f8aca26bf3c9f837e3e396/src/grafana_dashboards/alertmanager_rev4.json.tmpl#L11160).

But I'm not clear on the use case. Why would you want to do that? The means of differentiating one instance from another is via the dashboard dropdowns.

**Comment by chanchiwai-ray** [comment]
I think the active provisioning system in Grafana don't like the dashboards with the same title: see issue #303

**Comment by lucabello** [comment]
Closing because I believe this is solved via the suggestions above; please feel free to reopen if this is still an issue!
