### ISSUE TITLE
Recreating grafana pods leads to deleting non default organisation and users

### ISSUE THREAD

**Issue by err404r** [canonical/grafana-k8s-operator#313]
### Bug Description

Deleting grafana pod when grafana 9.5.3 is used, leading to removal all custom user and organisations.
We are suspecting that the issue is related to grafana image it is happening with resource revision 67 and 68 but not happening with 63 the charm is latest/stable rev 105

### To Reproduce

1. Deploy cos bundle with the latest stable, make sure that PVs for grafana are created correctly and working
2. Create user and/or organisation through grafana web UI
3. delete grafana pod 'kubectl delete pod -n cos grafana-0`
4. After pod is recreated all users is gone

### Environment

Grafana charm latest/stabel rev 105

### Relevant log output

```shell
I wasn't able to capture logs related to the issue
```

**Comment by peppepetra** [comment]
A possible workaround is to downgrade Grafana attaching a resource to the charm with

```
wget https://api.charmhub.io/api/v1/resources/download/charm_nuH5FwARV8dmAkPiPcVCNtPKwsw0bkgL.grafana-image_63
juju attach-resource grafana grafana-image=charm_nuH5FwARV8dmAkPiPcVCNtPKwsw0bkgL.grafana-image_63
```
