### ISSUE TITLE
Support integration with external identity providers

### ISSUE THREAD

**Issue by facundofc** [canonical/grafana-k8s-operator#324]
### Enhancement Proposal

Currently there's no way to make use of any external identity provider (like Azure Entra -former AD- for instance).

I've followed [this](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/azuread/) to manually add the configuration to `/etc/grafana/grafana-config.ini`, but deleting the pod drops the changes.

A stopgap solution to this could be to use a persisted location for the config file so at least after manual configuration it remains.

**Comment by simskij** [comment]
Hi, you should not do this by mutating the ini, but using the identity platform charms. See https://charmhub.io/topics/canonical-identity-platform/how-to/integrate-external-identity-provider

**Comment by shipperizer** [comment]
hi @facundofc as Simon said, the idea is to integrate with the Identity Team charms and then configure one of our components to integrate with the external IDP 

 if you need any support you can find us on matrix https://matrix.to/#/!nRbdoDYxdQndEfzlJi:ubuntu.com?via=ubuntu.com&via=matrix.org&via=mozilla.org

feel free to reach out

**Comment by mmkay** [comment]
Closing as explained by @shipperizer and @simskij.
