### ISSUE TITLE
add option --disable-reporting to the command line via charm configuration switch

### ISSUE THREAD

**Issue by mastier** [canonical/grafana-k8s-operator#353]
### Enhancement Proposal

Currently grafana (as well as [grafana-agent](https://github.com/canonical/grafana-agent-operator/issues/197)) calls home (sends anonymous usage statistics) to stats.grafana.org
Our customer does not want any application to call home.

More details available here:
https://grafana.com/docs/alloy/latest/data-collection/

So essentially the charm should have option to --disable-reporting to the command line.

Marking it as field-critical as it required for the closing deployment in 2 weeks.

**Comment by simskij** [comment]
@sed-i this is related to https://github.com/canonical/grafana-agent-operator/issues/197 and should probably be prioritized and done together.
