### ISSUE TITLE
Lock Grafana into single node or HA mode from the start

### ISSUE THREAD

**Issue by justinmclark** [canonical/grafana-k8s-operator#5]
Based on the team review of this charm, we need to lock the setting of Grafana into HA or single node mode because if it starts in single node mode and then scales up, we would need to migrate the `sqlite3` database to the `mysql` or `postgres` database.

However, we need to have goal-state exposed in OF to accomplish this. Blocked for now (as of Nov. 12, 2020).

**Comment by rbarry82** [comment]
No longer needed with `litestream` for replication in the lite version
