### ISSUE TITLE
Inject Juju topology label filters for widgets that use a datasource of type prometheus

### ISSUE THREAD

**Issue by mmanciop** [canonical/grafana-k8s-operator#51]
The [PromQL transform](https://github.com/canonical/promql-transform) utility allows to inject label filters into PromQL queries. This, coupled with the already-existing [Juju topology variables](https://github.com/canonical/grafana-k8s-operator/blob/819fdf06b2e1ed55d312c4e5f8e2e58a967cb7fd/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L52) that are automatically injected by the `grafana-dashboard` library, will result in automatically applying the values of those dashboard variables to the widgets without any additional work by charm authors.

**Comment by simskij** [comment]
One thing to keep in mind with this approach is that if a user relates two applications of the same type, we'd need to keep multiple copies of the same dashboard, but with different label matchers injected.

**Comment by simskij** [comment]
Read the issue a bit closer, and with variables rather than actual values my previous comment does not apply.
