### ISSUE TITLE
The get-admin-password actions returns incorrect information during deployment

### ISSUE THREAD

**Issue by simskij** [canonical/grafana-k8s-operator#75]
### Bug Description

The get-admin-password action returns "Admin password has been changed by an administrator" during deployment. It also reports this message in the admin-password field, which seems a bit counter-intuitive and might make it less straightforward to use in scripts.

### To Reproduce

1. `juju deploy grafana-k8s --channel edge`
2. `juju run-action grafana-k8s/0 get-admin-password --wait`

### Environment

Using grafana-k8s from `latest/edge`.

### Relevant log output

```shell
michele@boombox:~/git/prometheus-operator$ juju run-action grafana/0 get-admin-password --wait
unit-grafana-0:
  UnitId: grafana/0
  id: "4"
  results:
    admin-password: Admin password has been changed by an administrator
  status: completed
  timing:
    completed: 2022-03-15 08:56:52 +0000 UTC
    enqueued: 2022-03-15 08:56:50 +0000 UTC
    started: 2022-03-15 08:56:51 +0000 UTC
```

**Comment by rbarry82** [comment]
Closed by #76
