### ISSUE TITLE
Add jsonData support for Grafana Sources

### ISSUE THREAD

**Issue by mmanciop** [canonical/grafana-k8s-operator#88]
Grafana datasources accept additional configurations, called `jsonData`, that allow to specify additional configurations.

Of particular interest is the `jsonData` of the [Alertmanager datasource for Grafana 8](https://grafana.com/docs/grafana/latest/datasources/alertmanager/), where we will need to differentiate between Prometheus' and Cortex' Alertmanager.

**Comment by rbarry82** [comment]
Closed with #102
