### ISSUE TITLE
Suggested feature: Add convenience action for providing all login information

### ISSUE THREAD

**Issue by ca-scribner** [canonical/grafana-k8s-operator#92]
This is purely a suggestion for a convenience function.

The `get-admin-password` action is great for getting the grafana dashboard password, but whenever I use it I'm really looking for:
* password
* url
* login (I realise it is fixed, but for completeness...)

There are ways of getting the other info programatically (could use `juju` to get the unit IP), but I think in most cases when someone wants password they probably also want to know the dashboard url to use the password on.  Would be great if they were all returned together (either in `get-admin-password`, or in a similar `get-dashboard-login-details` or whatever)

**Comment by hemanthnakkina** [comment]
+1 on this suggestion, especially the URL is required for sunbeam and need to be exposed via an action.
